defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: my_app_development

test:
  <<: *defaults
  database: my_app_test

# set these environment variables on your prod server
production:
  uri: mongodb://root:admin@flame.mongohq.com:27037/hacknjill